services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - ./data/redis:/data
  api:
    image: capstone:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVICE=api