services:
  redis:
    image: redis:6.2-alpine
    restart: always
    volumes: 
      - ./data/redis:/data
  edge:
    image: capstone:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - REDIS_ADDR=redis:6379
      - SERVICE=edge
    ports:
      - 8080:8080
    depends_on:
      - redis
  api:
    image: capstone:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - REDIS_ADDR=redis:6379
      - SERVICE=api
    ports:
      - 8081:8080
    depends_on:
      - redis
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
